<a href="https://colab.research.google.com/github/Vishhwassri32/numpy__prasticse/blob/main/numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
students = np.array(["Aman", "Vishwas", "Priya", "Rohit", "Neha"])

# Marks: [Maths, Science, English]
marks = np.array([
    [78, 85, 90],
    [90, 88, 95],
    [65, 70, 60],
    [82, 79, 85],
    [95, 92, 98]
])


In [ ]:
np.sum(marks)

np.int64(1252)

In [ ]:
np.max

<function max at 0x78f2ae9ef670>

In [ ]:
np.min

<function min at 0x78f2ae9efa70>

In [ ]:
# 1. हर student का average marks
avg_marks = marks.mean(axis=1)
print("Average Marks of Students:", avg_marks)

# 2. हर subject का topper
subject_topper = marks.argmax(axis=0)
print("Maths Topper:", students[subject_topper[0]])
print("Science Topper:", students[subject_topper[1]])
print("English Topper:", students[subject_topper[2]])

# 3. Overall topper
overall_topper = avg_marks.argmax()
print("Overall Topper:", students[overall_topper])

# 4. Subject-wise average
subject_avg = marks.mean(axis=0)
print("Average in Maths, Science, English:", subject_avg)

# 5. Pass/Fail (assume pass = 40+ in all subjects)
pass_fail = np.all(marks >= 40, axis=1)
print("Pass/Fail Status:", pass_fail)


Average Marks of Students: [84.33333333 91.         65.         82.         95.        ]
Maths Topper: Neha
Science Topper: Neha
English Topper: Neha
Overall Topper: Neha
Average in Maths, Science, English: [82.  82.8 85.6]
Pass/Fail Status: [ True  True  True  True  True]


In [ ]:
dta=np.mean(marks)
print(dta)

83.46666666666667


In [ ]:
dte=np.median(marks)
print(dte)

85.0


In [ ]:
dte=np.std(marks)
print(dte)

10.91095270308184


In [ ]:
dte=np.var(marks)
print(dte)

119.0488888888889


In [ ]:
dte=np.min(marks)
print(" min marks ofsudent :",dte)
dte=np.max(marks)
print(" max marks ofsudent :",dte)

 min marks ofsudent : 60
 max marks ofsudent : 98


In [ ]:
s = np.array([ [5, 3, 4, 6, 7, 8, 9, 1, 2], [6, 7, 2, 1, 9, 5, 3, 4, 8], [1, 9, 8, 3, 4, 2, 5, 6, 7],

[8, 5, 9, 7, 6, 1, 4, 2, 3],
[4, 2, 6, 8, 5, 3, 7, 9, 1],
[7, 1, 3, 9, 2, 4, 8, 5, 6],

[9, 6, 1, 5, 3, 7, 2, 8, 4],
[2, 8, 7, 4, 1, 9, 6, 3, 5],
[3, 4, 5, 2, 8, 6, 1, 7, 9]])


In [4]:
import numpy as np
s = np.array([ [5, 3, 4, 6, 7, 8, 9, 1, 2], [6, 7, 2, 1, 9, 5, 3, 4, 8], [1, 9, 8, 3, 4, 2, 5, 6, 7],

[8, 5, 9, 7, 6, 1, 4, 2, 3],
[4, 2, 6, 8, 5, 3, 7, 9, 1],
[7, 1, 3, 9, 2, 4, 8, 5, 6],

[9, 6, 1, 5, 3, 7, 2, 8, 4],
[2, 8, 7, 4, 1, 9, 6, 3, 5],
[3, 4, 5, 2, 8, 6, 1, 7, 9]])

np.sum(s,axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [7]:
s = np.array([ [5, 3, 4, 6, 7, 8, 9, 1, 2], [6, 7, 2, 1, 9, 5, 3, 4, 8], [1, 9, 8, 3, 4, 2, 5, 6, 7],

[8, 5, 9, 7, 6, 1, 4, 2, 3],
[4, 2, 6, 8, 5, 3, 7, 9, 1],
[7, 1, 3, 9, 2, 4, 8, 5, 6],

[9, 6, 1, 5, 3, 7, 2, 8, 4],
[2, 8, 7, 4, 1, 9, 6, 3, 5],
[3, 4, 5, 2, 8, 6, 1, 7, 9]])
np.sum(s,axis=0)
np.sum(s,axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [8]:
s[1:4]

array([[6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3]])

In [15]:
import numpy as np
c=np.sum(s,axis=0)
for i in c:
  if i!=45:
    print("not valid" )
    break;
else:
      print("valid")


valid


In [16]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [23]:
np.shape(data)

(5, 3)

#Find the average age of students.
**bold text**

In [25]:
av=np.mean([data[:,0]])
print(av)

18.4


In [27]:
data[:,1]

array([85, 92, 76, 65, 90])

In [33]:
max_mrk=np.max(data[:,2])
print(max_mrk)

95
